# Previously generated by GoReleaser. Now maintained by hand: releases are built
# and published locally, so nothing regenerates this file. Update version and the
# four sha256 values on each release.
#
# Note: the macOS stanza is per-architecture. It previously pointed at
# ntm_<version>_darwin_all.tar.gz, a universal binary that recent releases have
# not shipped, so the cask was broken for every version after 1.18.3.
cask "ntm" do
  version "1.29.3"

  on_macos do
    on_intel do
      sha256 "da155a8d9800e4e627df665b0f4dd3cb66b33245bfdeca94b98b639211a65a04"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61c50a3e909ffcdcb2750c2a8aa1ff67c57ec110238ede6cac4ccb71ff7e00c5"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad6c10a95e69975f2c378d6a881beca63087f1f73faae29d4f793730c59f5e34"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "84148844702b67f870e405acde311e1d9dd8d4c39975172d1fd47aceb97bd10e"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"

  livecheck do
    skip "Updated manually on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "ntm"

  # No zap stanza required

  caveats <<~EOS
    To complete installation, add the following to your shell config:

      # For zsh (add to ~/.zshrc):
      eval "$(ntm shell zsh)"

      # For bash (add to ~/.bashrc):
      eval "$(ntm shell bash)"

    Run 'ntm tutorial' to get started!
  EOS
end
