# Previously generated by GoReleaser. Now maintained by hand: releases are built
# and published locally, so nothing regenerates this file. Update version and the
# four sha256 values on each release.
#
# Note: the macOS stanza is per-architecture. It previously pointed at
# ntm_<version>_darwin_all.tar.gz, a universal binary that recent releases have
# not shipped, so the cask was broken for every version after 1.18.3.
cask "ntm" do
  version "1.30.0"

  on_macos do
    on_intel do
      sha256 "c112aaa057f5821438836565a7423b9f9c5db99d27b85d40b69719aeddedab48"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dd54f8a2c1b4c88287f970905bb152289e2156bc2a6a3caf02724de3ae66a32"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "367432e6924fa80241a073d7708ce000195740b00d19008b051f6653c548d3e1"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51d90ef848af878b39b675b0608abedf090aa4ec70bde264c5ffdc7bb1729956"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"

  livecheck do
    skip "Updated manually on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "ntm"

  # No zap stanza required

  caveats <<~EOS
    To complete installation, add the following to your shell config:

      # For zsh (add to ~/.zshrc):
      eval "$(ntm shell zsh)"

      # For bash (add to ~/.bashrc):
      eval "$(ntm shell bash)"

    Run 'ntm tutorial' to get started!
  EOS
end
