# Previously generated by GoReleaser. Now maintained by hand: releases are built
# and published locally, so nothing regenerates this file. Update version and the
# four sha256 values on each release.
#
# Note: the macOS stanza is per-architecture. It previously pointed at
# ntm_<version>_darwin_all.tar.gz, a universal binary that recent releases have
# not shipped, so the cask was broken for every version after 1.18.3.
cask "ntm" do
  version "1.28.0"

  on_macos do
    on_intel do
      sha256 "c40097f937669b57c0f66dd94b4de1e65191a609d7d7b678da48fa84422494a7"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ced5917b5e85a2d4e17c8d0fc5aeb31e84c1ffcc842bfa217b6b0a67de31a370"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bb80190a165a7b05e5b61dfa014f821a6b6f4de99adf5c8d947da852144fa32"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9346661dc875bb3315019e38cd065b455df954fb15ba0598b4d2bdcccef2b674"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"

  livecheck do
    skip "Updated manually on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "ntm"

  # No zap stanza required

  caveats <<~EOS
    To complete installation, add the following to your shell config:

      # For zsh (add to ~/.zshrc):
      eval "$(ntm shell zsh)"

      # For bash (add to ~/.bashrc):
      eval "$(ntm shell bash)"

    Run 'ntm tutorial' to get started!
  EOS
end
