# Originally generated by GoReleaser; v0.4.1 hashes entered by hand from the release's checksums.txt.
cask "slb" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "6ac4ab8871214942bc3edde176b3605f84468106d99b8a19fb969f082da6608d"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d657a1818ceb928f412b9138abb9eda171b65745929fa3389aed397f2e2b2de6"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c398fb7f8d3bdaca8ad4e70497e84451609993eb5ba4e9b7cea52a8a7247972"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e689a8bd32c63dbbd01c02e8e63bcdb4264b33d57dd2736cee95e06cd4c5a3ea"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slb"
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slb"

  # No zap stanza required

  caveats <<~EOS
    SLB (Simultaneous Launch Button) implements two-person authorization.

    Quick start:
      slb init                  # Initialize in current project
      slb create "rm -rf /"     # Create a launch request
      slb list                  # List pending requests
  EOS
end
