# Originally generated by GoReleaser; v0.5.2 hashes entered by hand from the release's checksums.txt.
cask "slb" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "23ae548fc44b8a4df3aa9c0dd72151316443051252152864e18e9c42d20c21bc"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6e425605df4ea01fef10c701a139d282613aab22a3a7f49e8e5eb32d6e2f933"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18ff0daf113d2432538e46f3ad21c41a97c8891966da4febcf18d717a5b826ed"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff315e57f1c43ebc1acfb7cc26c1cfe8c6b2157300f77f5478c4c6ce59ba4967"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slb"
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slb"

  # No zap stanza required

  caveats <<~EOS
    SLB (Simultaneous Launch Button) implements two-person authorization.

    Quick start:
      slb init                  # Initialize in current project
      slb create "rm -rf /"     # Create a launch request
      slb list                  # List pending requests
  EOS
end
