# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bv < Formula
  desc "Graph-aware task management TUI for beads projects"
  homepage "https://github.com/Dicklesworthstone/beads_viewer"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.21.2/bv_darwin_amd64.tar.gz"
      sha256 "a7d74fcbc1072ee1c4038dc3af137de882f34fc17f6316d5a2865d415727b8f4"

      define_method(:install) do
        bin.install "bv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.21.2/bv_darwin_arm64.tar.gz"
      sha256 "1da8f6d028c5ec02c68ee923ce3b8c6c2efb8c7214a474208062098e21542d29"

      define_method(:install) do
        bin.install "bv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.21.2/bv_linux_amd64.tar.gz"
      sha256 "e5cf775a5e945fb9b29b06e45b2d14ab69788daa70d466d78d3c20cf99e48543"
      define_method(:install) do
        bin.install "bv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.21.2/bv_linux_arm64.tar.gz"
      sha256 "93f2d5bd1750bee8d1c66721e85a91747417a43b9da8166487a7fd867f8f323e"
      define_method(:install) do
        bin.install "bv"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with bv:
        1. Initialize beads in your project: br init
        2. Launch the TUI: bv

      For AI agent integration, use --robot-* flags:
        bv --robot-triage     # Get prioritized recommendations
        bv --robot-next       # Get single next action
    EOS
  end

  test do
    system "#{bin}/bv", "--version"
  end
end
