# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caam < Formula
  desc "CLI tool for managing AI coding agent accounts and configurations"
  homepage "https://github.com/Dicklesworthstone/coding_agent_account_manager"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.20/caam_0.1.20_darwin_amd64.tar.gz"
      sha256 "7bfdc8fe1c6696a387f1fa59d959906299725aa59fd3c75ab0a389216e8ece2b"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.20/caam_0.1.20_darwin_arm64.tar.gz"
      sha256 "2c6b7f6641351a983d0536aec2dd1a0ea0bf65a203438c34790f63c5a876e9b3"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.20/caam_0.1.20_linux_amd64.tar.gz"
      sha256 "9bbb64b14389f7927c79133b0f07c54f9f33adea5adc713a791be85a0e28620d"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.20/caam_0.1.20_linux_arm64.tar.gz"
      sha256 "c0349ac419cbc993f7d43de548bbfcb95e0eb738217bb3b9b99f2ab0bc5322a2"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To get started with caam:
        caam list              # List configured accounts
        caam switch <account>  # Switch to an account
        caam add               # Add a new account
    EOS
  end

  test do
    system "#{bin}/caam", "--version"
  end
end
