# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caam < Formula
  desc "CLI tool for managing AI coding agent accounts and configurations"
  homepage "https://github.com/Dicklesworthstone/coding_agent_account_manager"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.18/caam_0.1.18_darwin_amd64.tar.gz"
      sha256 "860138d80159689cccc98513e0a0f246ad98441a3f45caed756f209514bea972"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.18/caam_0.1.18_darwin_arm64.tar.gz"
      sha256 "f10acd6591aa808e4d486783e07695414b4ee92a28da697f33a86a83626f9106"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.18/caam_0.1.18_linux_amd64.tar.gz"
      sha256 "65aaccb12ca344dd64df8d378f2d79d9e305a5d7345cd47fe4ac8f361c3dc43c"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.18/caam_0.1.18_linux_arm64.tar.gz"
      sha256 "2ec69ee05a6e37b12b2c03d0e53a4f107d0627c218e5388d89be71d11e34cca7"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To get started with caam:
        caam list              # List configured accounts
        caam switch <account>  # Switch to an account
        caam add               # Add a new account
    EOS
  end

  test do
    system "#{bin}/caam", "--version"
  end
end
