# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caam < Formula
  desc "CLI tool for managing AI coding agent accounts and configurations"
  homepage "https://github.com/Dicklesworthstone/coding_agent_account_manager"
  version "0.1.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.21/caam_0.1.21_darwin_amd64.tar.gz"
      sha256 "6bb69e39c9d086f1e3e093d1195d35aede578a8634f0013e43010f2d98e7017c"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.21/caam_0.1.21_darwin_arm64.tar.gz"
      sha256 "03159b789cf445841c299435d74ef01480115eadd3cf4e910226b1a8fa7e2876"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.21/caam_0.1.21_linux_amd64.tar.gz"
      sha256 "bec85ccbddcd7a2cfcd3db137ea2dfb37c471dab875845cace626827913494ef"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.21/caam_0.1.21_linux_arm64.tar.gz"
      sha256 "c6c88af2e22ea96036bd8c74ba047043575a8734aabad747dbe9e53c832fcdad"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To get started with caam:
        caam list              # List configured accounts
        caam switch <account>  # Switch to an account
        caam add               # Add a new account
    EOS
  end

  test do
    system "#{bin}/caam", "--version"
  end
end
