# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slb < Formula
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"
  version "0.5.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.5.2/slb_0.5.2_darwin_amd64.tar.gz"
      sha256 "23ae548fc44b8a4df3aa9c0dd72151316443051252152864e18e9c42d20c21bc"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.5.2/slb_0.5.2_darwin_arm64.tar.gz"
      sha256 "e6e425605df4ea01fef10c701a139d282613aab22a3a7f49e8e5eb32d6e2f933"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.5.2/slb_0.5.2_linux_amd64.tar.gz"
      sha256 "18ff0daf113d2432538e46f3ad21c41a97c8891966da4febcf18d717a5b826ed"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.5.2/slb_0.5.2_linux_arm64.tar.gz"
      sha256 "ff315e57f1c43ebc1acfb7cc26c1cfe8c6b2157300f77f5478c4c6ce59ba4967"
    end
  end

  def install
    bin.install "slb"
    generate_completions_from_executable(bin/"slb", "completion")
  end

  def caveats
    <<~EOS
      SLB (Simultaneous Launch Button) implements two-person authorization.

      Quick start:
        slb init                  # Initialize in current project
        slb create "rm -rf /"     # Create a launch request
        slb list                  # List pending requests
    EOS
  end

  test do
    system bin/"slb", "version"
  end
end
