# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slb < Formula
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.4.1/slb_0.4.1_darwin_amd64.tar.gz"
      sha256 "6ac4ab8871214942bc3edde176b3605f84468106d99b8a19fb969f082da6608d"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.4.1/slb_0.4.1_darwin_arm64.tar.gz"
      sha256 "d657a1818ceb928f412b9138abb9eda171b65745929fa3389aed397f2e2b2de6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.4.1/slb_0.4.1_linux_amd64.tar.gz"
      sha256 "9c398fb7f8d3bdaca8ad4e70497e84451609993eb5ba4e9b7cea52a8a7247972"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/slb/releases/download/v0.4.1/slb_0.4.1_linux_arm64.tar.gz"
      sha256 "e689a8bd32c63dbbd01c02e8e63bcdb4264b33d57dd2736cee95e06cd4c5a3ea"
    end
  end

  def install
    bin.install "slb"
    generate_completions_from_executable(bin/"slb", "completion")
  end

  def caveats
    <<~EOS
      SLB (Simultaneous Launch Button) implements two-person authorization.

      Quick start:
        slb init                  # Initialize in current project
        slb create "rm -rf /"     # Create a launch request
        slb list                  # List pending requests
    EOS
  end

  test do
    system bin/"slb", "version"
  end
end
